name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  attestations: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0 (https://github.com/actions/checkout/releases/tag/v6.0.0)

      - name: Setup Node.js 24.x
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0 (https://github.com/actions/setup-node/releases/tag/v6.0.0)
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org/'

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44e0abb9eb2a0b8e0081c # v2.0.2 (https://github.com/oven-sh/setup-bun/releases/tag/v2.0.2)

      - name: Install Dependencies
        run: bun install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3 (https://github.com/changesets/action/releases/tag/v1.5.3)
        with:
          publish: bun release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: '' # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868
